setAs("character","myDate", function(from) as.Date(from, format="%d/%m/%Y") )
df<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",colClasses = c("myDate","character",rep("numeric",7)))
day1 = as.Date("2007-02-01")
day2 = as.Date("2007-02-02")
df = subset(df, Date %in% c(day1, day2))
hist(df$Global_active_power, col="red", xlab="Global Active Power (kilowatts)", main="Global Active Power")
dev.copy(png, file = "plot1.png")
dev.off()